### ISSUE TITLE
Some unit test failures

### ISSUE THREAD

**Issue by PVince81** [noveens/js-owncloud-client#22]
```
% make test
CONFIGS : 
{
    "owncloudURL": "http://127.0.0.1/owncloud",
    "username": "admin",
    "password": "admin"
}


> js-owncloud-client@1.0.0 test /home_ssd/vincent/work/workspace/js-owncloud-client
> jasmine ./owncloud/test/test.js

Started
...................F.............................................................................................................

Failures:
1) Currently testing apps management, checking method : non existent getAttribute
  Message:
    Expected 'value+plus space and/slash' to equal null.
  Stack:
    Error: Expected 'value+plus space and/slash' to equal null.
        at /home_ssd/vincent/work/workspace/js-owncloud-client/owncloud/test/test.js:328:18
        at tryCallOne (/home_ssd/vincent/work/workspace/js-owncloud-client/node_modules/promise/lib/core.js:37:12)
        at /home_ssd/vincent/work/workspace/js-owncloud-client/node_modules/promise/lib/core.js:123:15
        at flush (/home_ssd/vincent/work/workspace/js-owncloud-client/node_modules/promise/node_modules/asap/raw.js:50:29)

129 specs, 1 failure
Finished in 51.228 seconds

npm ERR! Test failed.  See above for more details.
Makefile:20: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by noveens** [comment]
@PVince81 ,
I can't reproduce this in any way, can you please run the tests once again to check if this is a persistent failure?

**Comment by PVince81** [comment]
Ran it again after cleaning up everything and resetting everything.
Still getting this:
```
Failures:
1) Currently testing apps management, checking method : non existent getAttribute
  Message:
    Expected 'value+plus space and/slash' to equal null.
  Stack:
    Error: Expected 'value+plus space and/slash' to equal null.
        at oc.apps.getAttribute.then.data (/home/vincent/work/workspace/js-owncloud-client/owncloud/test/test.js:334:18)
        at tryCallOne (/home/vincent/work/workspace/js-owncloud-client/node_modules/promise/lib/core.js:37:12)
        at /home/vincent/work/workspace/js-owncloud-client/node_modules/promise/lib/core.js:123:15
        at flush (/home/vincent/work/workspace/js-owncloud-client/node_modules/asap/raw.js:50:29)

129 specs, 1 failure
Finished in 73.697 seconds
```

**Comment by noveens** [comment]
@PVince81 
I just updated my OC instance to the latest dev version, still, all tests pass. can you please specify your OC instance version?

**Comment by noveens** [comment]
@PVince81 ,
Can you come online to the IRC, need to talk, shows you're offline.

**Comment by noveens** [comment]
@PVince81 ,

I can't seem to find any reason, can you please help me in debugging this?
Debugging suggestion: try `console.log(send)` in file: owncloud/appManagement.js Line Number-94.
https://github.com/noveens/js-owncloud-client/blob/master/owncloud/appManagement.js#L94

Just check if at one instance, there should be: `getattribute/someAppName1498583952XXX/attr%2Bplus%20space%20` (Mind the %20 at the end)

Please respond back when you find time.
Thanks.

**Comment by noveens** [comment]
@PVince81 ,
Please look into this.

**Comment by PVince81** [comment]
closing in favor of https://github.com/noveens/js-owncloud-client/issues/39
